version: '3'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
        - /tmp/data:/var/lib/mysql
        - /tmp/logs:/var/logs

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080